# fly.toml app configuration file generated for deeplink-redirect on 2025-02-28T15:44:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deeplink-redirect'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
